# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.7.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
        services:
          - db
          - redis
definitions:
  services:
    db:
      image: mariadb:10.3
      environment:
        MYSQL_ROOT_PASSWORD: areallystrongpassword
        MYSQL_DATABASE: get_help
        MYSQL_USER: get_help
        MYSQL_PASSWORD: get_help
    redis:
      image: redis:4-alpine

