version: '3'
services:
    app:
        build: .
        volumes:
            - "./:/app"
        command: ["npm", "run", "watch"]
        links:
            - db
            - redis
        ports:
            - "3001:3000"
            - "9229:9229"
    db:
        image: mariadb:10.3
        volumes: 
            - "db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: areallystrongpassword
            MYSQL_DATABASE: get_help
            MYSQL_USER: get_help
            MYSQL_PASSWORD: get_help
            REDIS_HOST: redis
        ports:
            - "3306:3306"
    redis:
        image: redis:4-alpine
        ports:
            - "6379:6379"
    api_docs:
        image: swaggerapi/swagger-ui
        volumes:
            - ./swagger.json:/tmp/swagger.json
        environment:
            SWAGGER_JSON: /tmp/swagger.json
        ports:
            - "3002:8080"
    api_editor:
        image: swaggerapi/swagger-editor
        ports:
            - "3003:8080"
volumes:
    db:
        driver:
            local

